version: '3.8'

services:
  api_dev:
    build:
      context: .
      target: build
    ports:
      - "8081:8080"
    command: sleep 3600
    restart: always
    environment:
      DB_USER: sa
      DB_PASSWORD:
    volumes:
      - .:/app

  api:
    build: .
    restart:  on-failure
    ports:
      - "8080:8080"
    environment:
      DB_USER: sa
      DB_PASSWORD:

volumes:
  db-data: